image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install && npm build
        artifacts:
          - build/**

    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:0.3.3
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: 'tech-bbq'
